name: Rust CI with Miri

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Miri and Clippy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust: [stable, nightly]

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Rust toolchain
      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      # Step 3: Install Miri for nightly
      - name: Install Miri
        if: matrix.rust == 'nightly'
        run: |
          rustup component add miri
          rustup component add rust-src

      # Step 4: Install Clippy for stable
      - name: Install Clippy
        if: matrix.rust == 'stable'
        run: rustup component add clippy

      # Step 5: Run Clippy (Lint checks)
      - name: Run Clippy
        if: matrix.rust == 'stable'
        run: cargo clippy --all-targets --all-features -- -D warnings

      # Step 6: Run Miri (Test memory safety)
      - name: Run Miri
        if: matrix.rust == 'nightly'
        run: |
          cargo miri setup
          cargo miri test
